### ISSUE TITLE
ReferenceError: webpackJsonp is not defined

### ISSUE THREAD

**Issue by innomon** [jomendez/ionic-starters-support#1]
**Starter Name**
ionAppFullPlus 1.0.1 

**Ionic Info**
ionic info
`
cli packages: (/home/ashish/.nvm/versions/node/v8.11.1/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.11
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.11.1
    npm  : 6.4.0 
    OS   : Linux 4.4

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
`

**Describe the bug**
Run time error on  ionic serve command:
ReferenceError: webpackJsonp is not defined
    at http://localhost:8100/build/main.js:1:1

**To Reproduce**
run command `ionic serve`
The browser displays the runtime error

**Expected behavior**
should display app.

**Screenshots**
![image](https://user-images.githubusercontent.com/3252607/44786708-978e1680-abb2-11e8-84b7-8f59bc1a99a3.png)

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Browser [ chrome]
 - Version [Version 68.0.3440.106 (Official Build) (64-bit)]

**Additional context**
bought the app today 29-aug-2018

**Comment by jomendez** [comment]
Thank for open an issue with us.

This is an environment issue that is present from ionic version 3.6.0 and up. I thought I fixed this issue for the starter long time ago, anyhow, please make sure that in src/index.html there is a reference to build/vendor.js 

![image](https://user-images.githubusercontent.com/8228498/44792816-be2c5d00-ab72-11e8-8ef3-409d9237b24e.png)
If not, please include it as shown on image above 

If your issue persist, check out this discussions from other developers having the same issue:
https://forum.ionicframework.com/t/uncaught-referenceerror-webpackjsonp-is-not-defined/100346/5
https://github.com/ionic-team/ionic/issues/12889
https://stackoverflow.com/questions/44988166/ionic-2-referenceerror-webpackjsonp-is-not-defined

**Comment by innomon** [comment]
The version 1.0.2 does not have this issue. Thanks.

**Comment by innomon** [comment]
The version 1.0.2 solved this issue. Thanks.
